language: python
branches:
  only:
  - master
notifications:
  email: false
addons:
  apt:
    packages:
    - xsltproc
before_install:
  - wget http://mirror.pnl.gov/macports/distfiles/texml/texml-2.0.2.tar.gz && tar xfzv texml-2.0.2.tar.gz && cd texml-2.0.2 && sudo python setup.py install && sudo ln -s /usr/local/bin/texml /usr/bin/texml && cd ~
install:
- pip install pelican ghp-import markdown
script:
- make github
env:
  global:
    secure: cbcSKjgyE15JRufgwi+UYO7OCa70SZr9zN3tw9dzzdlCfoYpwEqV3tyQSF2voqZUL8qd0JV7EBPQa7SEpqBgvtSJUPewfm0n8yLJJ5mPDyS3UCRhLJHeVnsQtDGAuLg/Pl1skCUKZxU8CuKPXBij/zvwMEL5aS/wWI+RVrtXMGM=     
