language: python
branches:
  only:
  - master
notifications:
  email: false
addons:
  apt:
    packages:
    - xsltproc
install:
- pip install pelican ghp-import markdown
script:
- make github
env:
  global:
    secure: cbcSKjgyE15JRufgwi+UYO7OCa70SZr9zN3tw9dzzdlCfoYpwEqV3tyQSF2voqZUL8qd0JV7EBPQa7SEpqBgvtSJUPewfm0n8yLJJ5mPDyS3UCRhLJHeVnsQtDGAuLg/Pl1skCUKZxU8CuKPXBij/zvwMEL5aS/wWI+RVrtXMGM=     
