# theme.toml template for xmpp.org’s Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "xmpp.org"
license = "MIT"
licenselink = "https://github.com/xsf/xmpp.org/themes/xmpp.org/blob/master/LICENSE"
description = "Hugo theme for xmpp.org"
homepage = "https://xmpp.org"
tags = []
features = []
min_version = "0.80.0"

[author]
  name = "XMPP Standards Foundation (XSF)"
  homepage = "https://xmpp.org"
