name: lint software lists
on:
  pull_request:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Software list linting
        run: |
          python tools/lint_list.py clients.json
          python tools/lint_list.py servers.json
          python tools/lint_list.py libraries.json
